name: kols-classic-testing/Ant-CI
on:
  workflow_dispatch:
env:
  system_debug: 'false'
jobs:
  Phase_1:
    name: pipelin-migrat
    runs-on:
      - self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Setup Java 16
      uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '16'
    - name: Ant  build.xml
      run: ant -buildfile build.xml
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.12.0
      if: always()
      with:
        junit_files: "**/TEST-*.xml"
