name: kols-classic-testing/delete-files-CI
on:
  workflow_dispatch:
env:
  system_debug: 'false'
jobs:
  Phase_1:
    name: pipelin-migrat
    runs-on:
      - self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Delete files
      uses: actions/github-script@v7.0.0
      env:
        REMOVE_SOURCE_FOLDER: false
        SOURCE_FOLDER: "."
        FILE_PATTERNS: |-
          myFileShare
          !**/.*
      with:
        script: |-
          const fs = require('fs')
          const sourceFolder = process.env.SOURCE_FOLDER
          process.chdir(sourceFolder)
          const removeSourceFolder = process.env.REMOVE_SOURCE_FOLDER
          const globber = await glob.create(process.env.FILE_PATTERNS)
          const files = await globber.glob()
          files.sort().reverse()
          for (file of files) {
              console.log(`deleting ${file}`)
              await io.rmRF(file)
          }
          if (removeSourceFolder == "true" && sourceFolder !== ".") {
              if (fs.readdirSync(".").length === 0) {
                  process.chdir("${{ github.workspace }}")
                  console.log(`deleting ${sourceFolder}`)
                  await io.rmRF(sourceFolder)
              }
          }
