name: kols-classic-testing/npm-CI
on:
  workflow_dispatch:
env:
  system_debug: 'false'
jobs:
  Phase_1:
    name: pipelin-migrat
    runs-on:
      - self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: npm install
      run: npm install
