name: kols-classic-testing/publish-build-artifacts-latest-CI
on:
  workflow_dispatch:
env:
  system_debug: 'false'
jobs:
  Phase_1:
    name: pipelin-migrat
    runs-on:
      - self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v4.1.0
      with:
        name: drop
        path: "${{ runner.temp }}"
